//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IgoraSoftware.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoginHistory_Log
    {
        public int UserId { get; set; }
        public System.DateTime LoginTime { get; set; }
        public int TypeLogin { get; set; }
    
        public virtual TypeLogin TypeLogin1 { get; set; }
    }
}
