//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IgoraSoftware.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class IgoraEntities : DbContext
    {
        public IgoraEntities()
            : base("name=IgoraEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Clients> Clients { get; set; }
        public virtual DbSet<LoginHistory_Log> LoginHistory_Log { get; set; }
        public virtual DbSet<Order> Order { get; set; }
        public virtual DbSet<Orders_Log> Orders_Log { get; set; }
        public virtual DbSet<PassportData> PassportData { get; set; }
        public virtual DbSet<Services> Services { get; set; }
        public virtual DbSet<Status> Status { get; set; }
        public virtual DbSet<TypeLogin> TypeLogin { get; set; }
        public virtual DbSet<UserRole> UserRole { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
